python ./RQ3B-Code/VulRepair/vulrepair_replication.py \
    --num_beams 50 \
    --output_dir=./RQ3B-Code/VulRepair/VulRepair_model/saved_models \
    --model_name=model.bin \
    --tokenizer_name=Salesforce/codet5-base \
    --model_name_or_path=Salesforce/codet5-base \
    --do_test \
    --test_data_file=./RQ3B-Dataset/test.csv \
    --encoder_block_size 512 \
    --decoder_block_size 256 \
    --eval_batch_size 1 \
    --n_gpu 1 \
    --seed 26312  2>&1 | tee ./RQ3B-Code/VulRepair/VulRepair_test.log
