python ./RQ3B-Code/CodeBERT/codebert_main.py \
    --beam_size 50 \
    --output_dir=./RQ3B-Code/CodeBERT/CodeBERT_model/saved_models \
    --model_name=model.bin \
    --tokenizer_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --do_test \
    --test_data_file=./RQ3B-Dataset/test.csv \
    --encoder_block_size 512 \
    --decoder_block_size 256 \
    --eval_batch_size 1 \
    --n_gpu 1 \
    --seed 26312  2>&1 | tee ./RQ3B-Code/CodeBERT/CodeBERT_test.log
